name: 'Amazon ECS "Deploy Task Definition" Action for GitHub Actions'
description: 'Registers an Amazon ECS task definition, and deploys it to an ECS service'
branding:
  icon: 'cloud'
  color: 'orange'
inputs:
  task-definition:
    description: 'The path to the ECS task definition file to register'
    required: true
  service:
    description: 'The name of the ECS service to deploy to. The action will only register the task definition if no service is given.'
    required: false
  cluster:
    description: "The name of the ECS service's cluster.  Will default to the 'default' cluster"
    required: false
  codedeploy-appspec:
    description: "The path to the AWS CodeDeploy AppSpec file, if the ECS service uses the CODE_DEPLOY deployment controller. Will default to 'appspec.yaml'."
    required: false
  codedeploy-application:
    description: "The name of the AWS CodeDeploy application, if the ECS service uses the CODE_DEPLOY deployment controller. Will default to 'AppECS-{cluster}-{service}'."
    required: false
  codedeploy-deployment-group:
    description: "The name of the AWS CodeDeploy deployment group, if the ECS service uses the CODE_DEPLOY deployment controller. Will default to 'DgpECS-{cluster}-{service}'."
    required: false
  codedeploy-deployment-description:
    description: "A description of the deployment, if the ECS service uses the CODE_DEPLOY deployment controller."
    required: false
  force-new-deployment:
    description: 'Whether to force a new deployment of the service. Valid value is "true". Will default to not force a new deployment.'
    required: false
outputs:
  deployment-platform:
    description: 'The platform being deployed to from this action (either AWS:ECS for rolling deployments or AWS:CodeDeploy for blue/green deployments)'
  task-definition-arn:
    description: 'The ARN of the registered ECS task definition'
  codedeploy-deployment-id:
    description: 'The deployment ID of the CodeDeploy deployment (if the ECS service uses the CODE_DEPLOY deployment controller'
  region:
    description: 'The AWS region (example, us-west-2) where the deployment is being executed'
  cluster:
    description: "The name of the ECS service's cluster"
  service: 
    description: 'The name of the ECS service to deployed to'
  deployment-url:
    description: 'The URL to use for deployment progress tracking and debugging'

runs:
  using: 'node12'
  main: 'dist/index.js'
